language: objective-c
osx_image: xcode11.5
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator13.5
before_install:
  - gem install cocoapods
  - pod repo update
  - pod install
before_script: 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
script:
  - xcodebuild -showsdks
  - xcodebuild -workspace Poly.xcworkspace -scheme 'Debug' -sdk $IOS_SDK build analyze

